apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsup-website
  labels:
    app: tsup-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsup-website
  template:
    metadata:
      labels:
        app: tsup-website
    spec:
      containers:
      - name: tsup-website
        image: translinkstg.azurecr.io/tsup/website:1524
      imagePullSecrets:
      - name: acr-auth
---
kind: Service
apiVersion: v1
metadata:
  name: tsup-website-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    port: 5000
  selector:
    app: tsup-website
