apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsup-website-qa
  labels:
    app: tsup-website-qa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tsup-website-qa
  template:
    metadata:
      labels:
        app: tsup-website-qa
    spec:
      containers:
      - name: tsup-website-qa
        image: translinkstg.azurecr.io/tsup/website:1524
      imagePullSecrets:
      - name: acr-auth
---
kind: Service
apiVersion: v1
metadata:
  name: tsup-qa-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    port: 5010
  selector:
    app: tsup-website-qa
